Feat: Added onboarding screen
IbraDajani/appNews pull request #31
Opened 2022-07-24 07:50 UTC by IbraDajani

# 🚨 Fill in the fields below

[Create Onboarding screen with all categories](https://trello.com/c/mhQLqcT0/43-create-onboarding-screen-with-all-categories)

## Description

```
~> Created OnBoarding screen with all categories available for selection by the user. and Created source request
```

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

## Checklist

- [ ] PRODUCT

  - [ ] Put PR link on ticket
  - [ ] Move the ticket

- [ ] DEVELOPERS

  - [ ] My code follows the style guidelines of this project
  - [ ] I have performed a self-review of my own code
  - [ ] I have commented my code, particularly in hard-to-understand areas
  - [ ] My changes generate no new warnings and I added `TODO:`, `FIXME:`

- [ ] REVIEW
  - [ ] Add reviewers: The entire team and most influential people in the area/project
  - [ ] Assignees myself to it

🚨 - `Approve: Wait at least one influential in the project or more experienced`

# FRONTEND

## Design
![image](https://user-images.githubusercontent.com/75001910/180637593-b4901799-8756-441a-aee2-08cea8957049.png)

## Screenshot or video of your application

https://user-images.githubusercontent.com/75001910/180637605-4e700ec6-7c51-40e1-8b8a-05875e7cbe2d.mp4

2022-07-24 15:39 UTC, JeanSilvany approved these changes

2022-07-24 15:40 UTC, JeanSilvany commented
Good job!

2022-07-24 19:22 UTC, PedrozdR requested changes

2022-07-24 19:22 UTC, PedrozdR commented on src/screens/OnBoarding/index.tsx
> +import Text from '~/components/Text';
Maybe we can do the same that we did with the App screens. We may organize those components into a index file and export everything from there

2022-07-24 19:22 UTC, PedrozdR commented on src/screens/OnBoarding/index.tsx
> +            App<Text color="primary">News</Text>
Lets try to put this header text with other typography.

2022-07-24 19:22 UTC, PedrozdR commented on src/screens/OnBoarding/index.tsx
> +              </CategoryLabel>
We need to use some emojis following this label. The shortcut is Windows + . (dot) 👳🏻‍♂️

2022-07-24 19:22 UTC, PedrozdR commented on src/screens/OnBoarding/index.tsx
> +              </CategoryLabel>
And try to put these Categories with rounded containers, like circles. 
Following the layout below 
![image](https://user-images.githubusercontent.com/40049825/180662471-b24223db-37d6-4158-b85a-d1ca78fc9536.png)

2022-07-24 19:22 UTC, PedrozdR commented on src/screens/OnBoarding/index.tsx
> +            <Text typography="overline">Skip</Text>
The "skip" text button of the layout is with grey color. 
```suggestion
            <Text color={colors.grey} typography="overline">Skip</Text>
```

![image](https://user-images.githubusercontent.com/40049825/180662541-15efa4d4-e0a2-4b06-b8e6-3e2a5f920413.png)

2022-07-24 19:22 UTC, PedrozdR commented on src/screens/OnBoarding/useOnboardingController.tsx
> +  const handleCategoriesPick = (category: CategoriesProps) => () => {
May you explain this function for me please? kkkkk Why you are not using an array of string insted of a object?

2022-07-24 22:30 UTC, PedrozdR commented on src/screens/OnBoarding/index.tsx
> +            App<Text color="primary">News</Text>
Like a bold one

2022-07-24 23:16 UTC, IbraDajani commented on src/screens/OnBoarding/index.tsx
> +import Text from '~/components/Text';
Lets create a card for it

2022-07-24 23:17 UTC, IbraDajani commented on src/screens/OnBoarding/index.tsx
> +            App<Text color="primary">News</Text>
Agreed

2022-07-24 23:42 UTC, IbraDajani commented on src/screens/OnBoarding/useOnboardingController.tsx
> +  const handleCategoriesPick = (category: CategoriesProps) => () => {
Is easier to deal with add/remove items from an object than it is on an array...

that said, the function is simple

first, I check if the item the user pressed already exists in the object. if it exists, i create a copy of the whole object, delete the item and then setState the copy of the object, but this time, with the item removed. if it doens't exists, i just add it to the Object


like

item exists ? (remove it) : (add it)

2022-07-25 01:49 UTC, PedrozdR approved these changes

2022-07-25 01:49 UTC, PedrozdR commented on src/screens/OnBoarding/index.tsx
> +            App<Text color="primary">News</Text>
Both

2022-07-27 18:15 UTC, merged